import { IProduct } from "@shared/components/types";

export const catalogue: IProduct[] = [{
  id: 111,
  sectionId: 1,
  title: 'Melena de León - Frasco de 30ml con gotero',
  description: "Doble Extracto Concentrado. Ayuda a tu cerebro y mejora tu salud gastrointestinal.",
  discount: 15,
  price: 37700,
  priceDiscount: 32000,
  priceTransfer: 25600,
  plan: "6 x $5.333 sin interés",
  urlPhoto: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_melena_de_leon.jpg",
  urlThumbnail: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_melena_de_leon.jpg",
  isValid: true,
},
{
  id: 112,
  sectionId: 1,
  title: 'Cordyceps Militaris - Frasco de 30ml con gotero',
  description: "Doble Extracto Concentrado. Vigorizante, reduce la fatiga y estimula el sistema inmunológico.",
  discount: 15,
  price: 37700,
  priceDiscount: 32000,
  priceTransfer: 25600,
  plan: "6 x $5.333 sin interés",
  urlPhoto: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_cordyceps_militaris.jpg",
  urlThumbnail: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_cordyceps_militaris.jpg",
  isValid: true,
},
{
  id: 113,
  sectionId: 1,
  title: 'Reishi - Frasco de 30ml con gotero',
  description: "Doble Extracto Concentrado. Lucha contra el cáncer, mejora respuesta inmune y efecto antioxidante.",
  discount: 15,
  price: 37700,
  priceDiscount: 32000,
  priceTransfer: 25600,
  plan: "6 x $5.333 sin interés",
  urlPhoto: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_reishi.jpg",
  urlThumbnail: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_reishi.jpg",
  isValid: true,
},
{
  id: 115,
  sectionId: 1,
  title: 'Cola de Pavo - Frasco de 30ml con gotero',
  description: "Doble Extracto Concentrado. Potencia las defensas del sistema inmunológico y favorece la salud intestinal.",
  discount: 15,
  price: 37700,
  priceDiscount: 32000,
  priceTransfer: 25600,
  plan: "6 x $5.333 sin interés",
  urlPhoto: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_cola_de_pavo.jpg",
  urlThumbnail: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_cola_de_pavo.jpg",
  isValid: true,
},
{
  id: 116,
  sectionId: 1,
  title: 'Cola de Pavo - Frasco de 30ml con gotero',
  description: "Doble Extracto Concentrado. Potencia las defensas del sistema inmunológico y favorece la salud intestinal.",
  discount: 15,
  price: 37700,
  priceDiscount: 32000,
  priceTransfer: 25600,
  plan: "6 x $5.333 sin interés",
  urlPhoto: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_cola_de_pavo.jpg",
  urlThumbnail: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_cola_de_pavo.jpg",
  isValid: true,
},
{
  id: 117,
  sectionId: 1,
  title: 'Cola de Pavo - Frasco de 30ml con gotero',
  description: "Doble Extracto Concentrado. Potencia las defensas del sistema inmunológico y favorece la salud intestinal.",
  discount: 15,
  price: 37700,
  priceDiscount: 32000,
  priceTransfer: 25600,
  plan: "6 x $5.333 sin interés",
  urlPhoto: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_cola_de_pavo.jpg",
  urlThumbnail: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_cola_de_pavo.jpg",
  isValid: true,
},
{
  id: 118,
  sectionId: 1,
  title: 'Cola de Pavo - Frasco de 30ml con gotero',
  description: "Doble Extracto Concentrado. Potencia las defensas del sistema inmunológico y favorece la salud intestinal.",
  discount: 15,
  price: 37700,
  priceDiscount: 32000,
  priceTransfer: 25600,
  plan: "6 x $5.333 sin interés",
  urlPhoto: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_cola_de_pavo.jpg",
  urlThumbnail: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_cola_de_pavo.jpg",
  isValid: true,
},
{
  id: 119,
  sectionId: 1,
  title: 'Cola de Pavo - Frasco de 30ml con gotero',
  description: "Doble Extracto Concentrado. Potencia las defensas del sistema inmunológico y favorece la salud intestinal.",
  discount: 15,
  price: 37700,
  priceDiscount: 32000,
  priceTransfer: 25600,
  plan: "6 x $5.333 sin interés",
  urlPhoto: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_cola_de_pavo.jpg",
  urlThumbnail: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_cola_de_pavo.jpg",
  isValid: true,
},
{
  id: 120,
  sectionId: 1,
  title: 'Cola de Pavo - Frasco de 30ml con gotero',
  description: "Doble Extracto Concentrado. Potencia las defensas del sistema inmunológico y favorece la salud intestinal.",
  discount: 15,
  price: 37700,
  priceDiscount: 32000,
  priceTransfer: 25600,
  plan: "6 x $5.333 sin interés",
  urlPhoto: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_cola_de_pavo.jpg",
  urlThumbnail: "https://mundoadaptogenos.netlify.app/assets/img/thumbnail/frasco_cola_de_pavo.jpg",
  isValid: true,
},
]